version: "3"
services:
  app:
    container_name: docker-node-mongo
    environment:
      - DATABASE_URL_DOCKER=mongodb://mongo:27017/subscribers
    restart: always
    build: .
    ports:
      - "8080:8080"
    external_links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"
