version: "3"
services:
  app:
    container_name: docker-node-mongo
    restart: always
    build: .
    # ports:
    #   - "80:3000"
    ports:
      - "3000:8080"
    external_links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"
      # ports:
      #   - "27017:27017"
#       services:
#   boilerplate-api-app:
#     build: .
#     environment:
#       - MONGO_URI=mongodb://mongodb-myapp:27017/myapp
#     volumes:
#       - .:/app
#     ports:
#       - "5000:5000"
#     depends_on:
#       - mongodb-myapp

#  mongodb-myapp:
#     image: mongo
#     ports:
#       - "27017:27017"
